language: python
python:
  - "3.7.3"  
# command to install dependencies

install:
  - pip install pipenv
  - pipenv install

# command to run tests
script:
  - pytest -s -v

notifications:
  email:
    - ykhorizon.light@gmail.com
