  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/python       
      steps:
        - checkout # check out the code in the project directory
        - run:
            name: Install pipenv 
            command: pip install pipenv
        - run:
            name: Install Package
            command: pipenv install
        - run: 
            name: Run testing
            command: pytest -s -v
